# Starter pipeline
- task: Npm@1
  inputs:
    command: 'install'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml 
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: '# Write your commands here
          
          # Use the environment variables input below to pass secret variables to this script
          node  -v 
          npm  -v 
          npx truffle version
          
          sed -i -e ''s/reporter: "spec"/reporter: "mocha-junit-reporter"/g'' truffle.js'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: '# Write your commands here
      npx truffle compile
      npx truffle  migrate --network localtest
      npx truffle test --network localtest
      
      
      # Use the environment variables input below to pass secret variables to this script'
  displayName: 'Run a multi-line script'
